"""add_live_state_to_workshop_rules

Revision ID: 59b3a5b0396b
Revises: 993f6fa74670
Create Date: 2026-02-13 20:04:09.296526

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59b3a5b0396b"
down_revision: Union[str, None] = "993f6fa74670"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workshop_rules",
        sa.Column(
            "all_muted", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "workshop_rules",
        sa.Column(
            "all_cameras_off",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workshop_rules", "all_cameras_off")
    op.drop_column("workshop_rules", "all_muted")
    # ### end Alembic commands ###
