"""add_video_models

Revision ID: 993f6fa74670
Revises: 6981675b6c6b
Create Date: 2026-02-08 11:52:04.338715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "993f6fa74670"
down_revision: Union[str, None] = "6981675b6c6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workshop_participant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("HOST", "PARTICIPANT", name="participantrole"),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workshop_participant_user_id"),
        "workshop_participant",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workshop_participant_workshop_id"),
        "workshop_participant",
        ["workshop_id"],
        unique=False,
    )
    op.create_table(
        "workshop_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("force_camera_on", sa.Boolean(), nullable=False),
        sa.Column("force_mic_muted_on_join", sa.Boolean(), nullable=False),
        sa.Column("allow_unmute_after", sa.Integer(), nullable=False),
        sa.Column("allow_camera_toggle", sa.Boolean(), nullable=False),
        sa.Column(
            "late_join_behavior",
            sa.Enum("ALLOW", "ALLOW_MUTED", "DENY", name="latejoinbehavior"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workshop_rules_workshop_id"),
        "workshop_rules",
        ["workshop_id"],
        unique=True,
    )
    op.add_column(
        "workshop",
        sa.Column("video_room_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workshop", "video_room_id")
    op.drop_index(op.f("ix_workshop_rules_workshop_id"), table_name="workshop_rules")
    op.drop_table("workshop_rules")
    op.drop_index(
        op.f("ix_workshop_participant_workshop_id"), table_name="workshop_participant"
    )
    op.drop_index(
        op.f("ix_workshop_participant_user_id"), table_name="workshop_participant"
    )
    op.drop_table("workshop_participant")
    # ### end Alembic commands ###
