"""add_deleted_at_to_workshop

Revision ID: c93be6b1f993
Revises: 8a6a02aec077
Create Date: 2026-03-22 13:57:17.030560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c93be6b1f993'
down_revision: Union[str, None] = '8a6a02aec077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_workshop_deleted_at'), 'workshop', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workshop_deleted_at'), table_name='workshop')
    op.drop_column('workshop', 'deleted_at')
    # ### end Alembic commands ###
