from enum import Enum


class ErrorCode(str, Enum):
    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_INVALID_TYPE = "TOKEN_INVALID_TYPE"
    TOKEN_REFRESH_INVALID = "TOKEN_REFRESH_INVALID"
    GOOGLE_TOKEN_INVALID = "GOOGLE_TOKEN_INVALID"
    GOOGLE_TOKEN_WRONG_AUDIENCE = "GOOGLE_TOKEN_WRONG_AUDIENCE"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    GOOGLE_ACCOUNT_CONFLICT = "GOOGLE_ACCOUNT_CONFLICT"
    PASSWORD_RESET_TOKEN_INVALID = "PASSWORD_RESET_TOKEN_INVALID"

    # Users
    USER_NOT_FOUND = "USER_NOT_FOUND"

    # Workshops
    WORKSHOP_NOT_FOUND = "WORKSHOP_NOT_FOUND"
    WORKSHOP_NOT_OWNER = "WORKSHOP_NOT_OWNER"
    WORKSHOP_LIVE = "WORKSHOP_LIVE"
    WORKSHOP_FULL = "WORKSHOP_FULL"
    WORKSHOP_ALREADY_STARTED = "WORKSHOP_ALREADY_STARTED"
    WORKSHOP_NOT_STARTED = "WORKSHOP_NOT_STARTED"
    WORKSHOP_ENDED = "WORKSHOP_ENDED"
    WORKSHOP_ENROLL_OWN = "WORKSHOP_ENROLL_OWN"
    WORKSHOP_ENROLL_NOT_MEMBER = "WORKSHOP_ENROLL_NOT_MEMBER"
    WORKSHOP_INVALID_START_TIME = "WORKSHOP_INVALID_START_TIME"
    WORKSHOP_GROUP_NOT_OWNED = "WORKSHOP_GROUP_NOT_OWNED"
    INVALID_DATE_RANGE = "INVALID_DATE_RANGE"

    # Groups
    GROUP_NOT_FOUND = "GROUP_NOT_FOUND"
    GROUP_NOT_OWNER = "GROUP_NOT_OWNER"
    GROUP_HAS_LIVE_WORKSHOP = "GROUP_HAS_LIVE_WORKSHOP"
    GROUP_NOT_MEMBER = "GROUP_NOT_MEMBER"
    GROUP_SUBSCRIBE_OWN = "GROUP_SUBSCRIBE_OWN"

    # Video
    VIDEO_SERVICE_UNAVAILABLE = "VIDEO_SERVICE_UNAVAILABLE"
    VIDEO_USAGE_LIMIT = "VIDEO_USAGE_LIMIT"
    PARTICIPANT_KICKED = "PARTICIPANT_KICKED"
    HOST_ACTION_FORBIDDEN = "HOST_ACTION_FORBIDDEN"
    HOST_ACTION_MISSING_TARGET = "HOST_ACTION_MISSING_TARGET"
    HOST_ACTION_SELF_REMOVE = "HOST_ACTION_SELF_REMOVE"

    # Webhook
    WEBHOOK_NOT_CONFIGURED = "WEBHOOK_NOT_CONFIGURED"
    WEBHOOK_SIGNATURE_INVALID = "WEBHOOK_SIGNATURE_INVALID"

    # Trainer
    TRAINER_REQUIRED = "TRAINER_REQUIRED"

    # Notifications / Push
    NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"
    PUSH_TOKEN_SERVICE_UNAVAILABLE = "PUSH_TOKEN_SERVICE_UNAVAILABLE"

    # Rate limiting
    RATE_LIMIT_AUTH = "RATE_LIMIT_AUTH"
    RATE_LIMIT_PASSWORD_RESET = "RATE_LIMIT_PASSWORD_RESET"
    RATE_LIMIT_PUSH_TOKEN = "RATE_LIMIT_PUSH_TOKEN"
